export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'


export const FETCH_LESSON_REQUEST = 'FETCH_LESSON_REQUEST'
export const FETCH_LESSON_FAILURE = 'FETCH_LESSON_FAILURE'
export const FETCH_LESSON_SUCCESS = 'FETCH_LESSON_SUCCESS'
